### PR TITLE
Don't export functions created with setGeneric()

### PR DESCRIPTION
**Pull request by hadley**
I'm pretty sure these are not necessary, and are actually harmful because they cause conflicts to be reported where conflicts don't actually exist. I confirmed this by reinstalling then running the following code:

``` r
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following object is masked from 'package:base':
#> 
#>     date
int1 <- interval(ymd("2001-01-01"), ymd("2002-01-01"))
int2 <- interval(ymd("2001-06-01"), ymd("2002-01-01"))
intersect(int1, int2)
#> [1] 2001-06-01 UTC--2002-01-01 UTC
```

### CODE REVIEW

**Comment by vspinu** [comment]
Does this help with #693?

**Comment by vspinu** [comment]
So could this be merged, or we are waiting for Jim to comment on this one?

Fine with me either way. I am not developing for R momentary so please take your time if you need.

**Comment by hadley** [comment]
Let's let this sit for a while.

**Comment by hadley** [comment]
Ok, now I see:

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following objects are masked from 'package:base':
#> 
#>     date, intersect, setdiff, union

int1 <- interval(ymd("2001-01-01"), ymd("2002-01-01"))
int2 <- interval(ymd("2001-06-01"), ymd("2002-01-01"))
intersect(int1, int2)
#> [1] 2001-06-01 UTC--2002-01-01 UTC
```

<sup>Created on 2019-11-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by vspinu** [comment]
There is a new [revdep failure](https://github.com/tidyverse/lubridate/blob/bf9db3cb1cdbe270319936849de7431a054b5414/revdep/problems.md#xroi) most likely due to this change. Any ideas what is going on? Can this be fixed on our side?

**Comment by vspinu** [comment]
My understanding is that `raster` defines its own generics, and thus overwrites ours when [xROI](https://github.com/bnasr/xROI/blob/master/DESCRIPTION) imports both packages. Looks to mem that we cannot do much here. It should be fixed on xROI or, better, on `raster` package, which should be ported on top of `generics`.

**Comment by hadley** [comment]
Yeah, agreed.

**Comment by vspinu** [comment]
https://github.com/rspatial/raster/issues/107

**Pull request merged**
