### PR TITLE
Refactors `quarter()` API to allow for quarter start- and end-dates

### PR DESCRIPTION
**Pull request by tomcardoso**
Addresses https://github.com/tidyverse/lubridate/issues/947. With this, the API now looks like:
```r
quarter(x) # default behaviour is unchanged
quarter(x, type = "quarter_year") # equivalent to what would previously be passing `with_year = TRUE`
quarter(x, type = "date_first") # new functionality
quarter(x, type = "date_last") # new functionality
```
The `with_year` parameter is soft-deprecated, but will continue to work for the time being.

### CODE REVIEW

**Comment by tomcardoso** [comment]
One thing: I tried running `pkgdown::build_site()` but got an error about tidytemplate not being installed. Is rebuilding docs something that happens separately from the PR?

**Comment by DavisVaughan** [comment]
FWIW these capabilities come built into [clock](https://github.com/r-lib/clock), where the year-quarter-day calendar is a first class type.

``` r
library(clock)
library(lubridate)

x <- as.Date("2019-04-25")

yqd1 <- as_year_quarter_day(x)
yqd1
#> <year_quarter_day<January><day>[1]>
#> [1] "2019-Q2-25"

# Get the quarter
quarter(x)
#> [1] 2
get_quarter(yqd1)
#> [1] 2

# Change the fiscal start month and try again
yqd2 <- as_year_quarter_day(x, start = clock_months$april)
yqd2
#> <year_quarter_day<April><day>[1]>
#> [1] "2020-Q1-25"

quarter(x, fiscal_start = 4)
#> [1] 1
get_quarter(yqd2)
#> [1] 1

# Get the year+quarter
quarter(x, type = "quarter_year")
#> [1] 2019.2
paste0(get_year(yqd1), ".", get_quarter(yqd1))
#> [1] "2019.2"

# or, more appropriately:
calendar_narrow(yqd1, "quarter")
#> <year_quarter_day<January><quarter>[1]>
#> [1] "2019-Q2"

# Get the first day of the quarter
quarter(x, type = "date_first")
#> [1] "2019-04-01"
as.Date(set_day(yqd1, 1))
#> [1] "2019-04-01"

# Get the last day of the quarter
quarter(x, type = "date_last")
#> [1] "2019-06-30"
as.Date(set_day(yqd1, "last"))
#> [1] "2019-06-30"
```

<sup>Created on 2021-03-03 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by tomcardoso** [comment]
@DavisVaughan Neat! Is the idea that `clock` would supersede `lubridate` eventually, since it's coming from the `r-lib` folks?

**Comment by DavisVaughan** [comment]
Not really supersede. Instead we currently are thinking of it as an alternative to lubridate, with lubridate still living on and being a powerful tool for working with date-times. In the far future, bits and pieces of lubridate (like this, for example) might end up relying on clock, but that is still a little uncertain.

**Comment by tomcardoso** [comment]
Hey @vspinu, any thoughts on this? Let me know if you want me to tweak anything.

**Comment by vspinu** [comment]
Sorry for delaying on this. There was an issue with the logical check which could fail for non-logical inputs. Also I don't quite like `quarter_year` because the return values is actually of the form `year.quarter`. So I have renamed that type. Please see my amendments. If it's ok with you I will merge.

**Comment by vspinu** [comment]
@tomcardoso you might have missed my last message. If you disagree with my amendments please let me know.

**Comment by tomcardoso** [comment]
Oh shoot, sorry @vspinu, I did miss this. Makes total sense to me – thanks for talking me through this stuff. Looking forward to putting the new functionality to use!

**Pull request merged**
